# Working with Data 1: NumPy

Last week we managed multi-value data with pure-Python lists, matrices and tensors. They work,
but Python itself is **slow** for heavy number crunching, and its built-in functions stop short
of serious mathematics. That is why nearly everyone working with numerical data uses **NumPy**:
its core is implemented in C (commonly dozens of times faster than plain Python loops) and it
ships with a huge library of mathematical operations.

In this lecture:

1. **What a library is**, and importing NumPy.
2. **Creating arrays** — vectors and matrices with `np.array`.
3. **Indexing and slicing** — just like lists.
4. **Adding and removing values** — `np.append`, `np.delete`.
5. **The shape of data** — reading `.shape` for vectors, matrices and tensors.
6. **Reshaping** — `reshape`, `flatten` and the transpose `.T`.
7. **Generating arrays** — `np.arange`.
8. **Filtering by condition** — `np.where` and boolean masks.

## 1. Libraries, and importing NumPy

A **library** is a ready-made collection of specialised functions. Instead of writing complex
mathematical routines ourselves, we *import* a library that already provides them, then call
its functions.

By convention everyone imports NumPy under the short alias `np`:

In [1]:
import numpy as np   # the universal convention - np saves a lot of typing

## 2. Creating arrays with `np.array`

`np.array()` builds an N-dimensional container from (possibly nested) lists — one function for
vectors, matrices and tensors alike:

In [2]:
np_list = np.array(["James", "Mikey", "Focus"])   # a 1-D array (vector)
print(np_list)
print(np_list.shape)   # .shape describes the structure - here: 3 elements, 1 dimension

['James' 'Mikey' 'Focus']
(3,)


In [3]:
np_array = np.array(
    [["tanakrit", "coding"], ["james", "basketball"], ["Mikey", "basketball"]]
)   # a 2-D array (matrix): a list of equal-sized lists
np_array

array([['tanakrit', 'coding'],
       ['james', 'basketball'],
       ['Mikey', 'basketball']], dtype='<U10')

## 3. Indexing and slicing

Everything you learned about list indexing transfers directly — including slices.
For 2-D arrays NumPy adds a nicer syntax: one bracket with a comma, `arr[row, column]`:

In [4]:
np_array[0]   # first row, exactly like a list

array(['tanakrit', 'coding'], dtype='<U10')

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])   # slicing a 1-D array, like a list

[2 3 4 5]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 0:10])   # row 0, columns 0-9 (a slice past the end just stops at the end)

[1 2 3]


## 4. Adding and removing values

NumPy arrays have a fixed size, so unlike `list.append`, the functions `np.append` and
`np.delete` build and **return a new array** — remember to store the result.
For 2-D arrays the `axis` argument says which direction to act along:
`axis=0` works on rows, `axis=1` on columns.

In [7]:
arr1d = [1, 2, 3, 4]
arr1d = np.append(arr1d, [123])   # returns a NEW array - reassign it
arr1d

array([  1,   2,   3,   4, 123])

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr = np.append(arr, [[7, 8, 9]], axis=0)   # add a row (axis=0)
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [9]:
arr = np.delete(arr, 0, axis=0)   # delete row 0
arr

array([[4, 5, 6],
       [7, 8, 9]])

## 5. The shape of data

Before processing an array we need to know **what it looks like** — vector, matrix or tensor,
and how big along each axis. `.shape` answers with one number per dimension.

A **vector** (1-D): one number in the result — a single row of 13 values:

In [10]:
onedarr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
onedarr.shape

(13,)

A **matrix** (2-D): two numbers — 3 rows and 5 columns. Think of a table:

In [11]:
twodarr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 3, 14, 15]])
twodarr.shape

(3, 5)

A **tensor** (3-D): three numbers — 3 layers of 3×5 matrices. Think of a cube of values:

In [12]:
threedarr = np.array(
    [
        [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 3, 14, 15]],
        [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 3, 14, 15]],
        [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 3, 14, 15]],
    ]
)
threedarr.shape

(3, 3, 5)

## 6. Reshaping arrays

`reshape()` rearranges the same values into a different shape. The one rule: the product of
the new dimensions must equal the number of elements — our 3×3×5 = 45 values can become
9×5, but not 8×5.

In [13]:
print(threedarr.shape)            # (3, 3, 5) - a tensor

reshaped = threedarr.reshape(9, 5)  # 3*3*5 = 45 = 9*5 -> allowed
reshaped

(3, 3, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12,  3, 14, 15],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12,  3, 14, 15],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12,  3, 14, 15]])

`flatten()` collapses any array into a single dimension:

In [14]:
flat = threedarr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  3, 14, 15,  1,  2,
        3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  3, 14, 15,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11, 12,  3, 14, 15])

### Transposing a matrix

The **transpose** swaps rows and columns — in NumPy, just append `.T`:

In [15]:
arr = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
arr   # 3 rows x 5 columns

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [16]:
arr.T   # 5 rows x 3 columns - rows and columns swapped

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

## 7. Generating arrays with `np.arange`

`np.arange` follows exactly the same rules as Python's `range()` — start, stop, step —
but produces a NumPy array directly:

In [17]:
print(np.arange(10))          # 0 to 9
print(np.arange(10, 50))      # 10 up to (not including) 50
print(np.arange(10, 50, 3))   # 10 to 49 in steps of 3

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


`arange` + `reshape` is a handy combo for generating structured test data:

In [18]:
x = np.arange(20)      # 1-D array of 20 values...
x = x.reshape(5, 4)    # ...reshaped into a 5x4 matrix
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## 8. Filtering with `np.where`

`np.where(condition)` returns the **positions** where a condition holds across the whole
array — no loop required. Feeding those positions back into the array extracts the matching
values. Here: all the even numbers from 1–29:

In [19]:
x = np.arange(1, 30)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
cond = np.where(x % 2 == 0)   # positions where the value is divisible by 2
cond

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27]),)

In [21]:
x[cond]   # feed the positions back in to extract the values

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

Even shorter — index directly with the boolean condition (a **boolean mask**).
This pattern is everywhere in data work, and next week pandas builds on it heavily:

In [22]:
x[x % 2 == 0]   # same result, one step

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

## Summary

| Task | Function / syntax |
|---|---|
| Create an array | `np.array([...])`, `np.arange(start, stop, step)` |
| Inspect structure | `.shape` — one number per dimension |
| Index / slice | `arr[i]`, `arr[a:b]`, `arr[row, col]` |
| Add / remove | `np.append(arr, vals, axis=...)`, `np.delete(arr, i, axis=...)` |
| Change shape | `reshape(r, c)`, `flatten()`, `.T` |
| Filter by condition | `np.where(cond)`, `arr[cond]` |

**Key takeaways**

- NumPy gives Python-style containers with C-level speed — the foundation of the entire
  scientific Python stack (the image-processing lectures later in this course run on it).
- `.shape` is the first thing to check on any array you receive.
- `reshape` only rearranges — the element count must stay the same.
- `np.append`/`np.delete` return **new** arrays; the `axis` argument picks rows vs columns.
- Boolean masks (`arr[arr % 2 == 0]`) replace whole filtering loops with one expression.

**Exercises**

1. Create `np.arange(1, 37)` and reshape it into a 6×6 matrix. What does `.T` look like?
2. From that matrix, slice out the central 2×2 block.
3. Use a boolean mask to extract all values greater than 20.
4. Why does `np.arange(10).reshape(3, 4)` fail? Fix it two different ways.

Next week: **pandas** — tables, CSV files and real datasets.